### ISSUE TITLE
I think there is an issue with your code in Kaggle, and the parameter here in PyTorch should be bool instead of str.

### ISSUE THREAD

**Issue by Cyberloafingg** [dipuk0506/UQ#1]
The code to load the data in the cifar-100 dataset is:
![image](https://github.com/dipuk0506/UQ/assets/73885115/d60fb222-f8b0-4228-8813-ecffbaa74b4f)
The following is the definition of the load function in PyTorch
![image](https://github.com/dipuk0506/UQ/assets/73885115/5bb5106e-b361-4dd7-b2c6-9dbcf2cd7ff3)
If you do it this way, train_data and test_data will become the same.

**Comment by dipuk0506** [comment]
Hi 涵泽,
Pytorch has provided different syntax for different datasets.

For STL-10 the syntax is:
data_train = datasets.STL10('/files/', split='train', download=True,
                             transform=transforms.Compose([ ]))

For CIFAR-10 the syntax is:
data_train = datasets.CIFAR10('/files/', train='True', download=True,
                             transform=transforms.Compose([ ]))

Also, in the logic, you provided, there are two list based on the Boolean train value.

**Comment by dipuk0506** [comment]
Hi Cyberloafingg,
I have changed notebooks with bool value. The problem occurs with CIFAR-10 and CIFAR-100 datasets. Other datasets are ok.  

Thank you for correcting me.
